###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: app-nyq-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

####swagger相关配置
swagger:
  base-package: com.nyq.member.service
  title: SpringCloud2.x构建微服务电商项目-微信服务接口
  description: 基于SpringCloud2.x构建微服务电商项目
  version: 1.1
  terms-of-service-url: 1234
  contact:
    name: nyq
    email: 11qq.com
           